local arch=$(uname -p 2>/dev/null)

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

[[ -f ~/.zshrc_local ]] && source ~/.zshrc_local

alias ls='/bin/ls -qAF'
alias mmv='noglob zmv -W'

# Ugh - prezto has -i as default
alias cp='nocorrect cp'
alias ln='nocorrect ln'
alias mv='nocorrect mv'
alias rm='nocorrect rm'


if (( $+commands[prettyping] )); then
    alias ping=prettyping
fi

if (( $+commands[htop] )); then
    alias top='sudo htop'
fi

[[ $EMACS = t ]] && unsetopt zle

if [ -f /opt/homebrew/bin/mise ]; then
  eval "$(/opt/homebrew/bin/mise activate --shims zsh)"
fi

if [ -f /opt/homebrew/bin/duf ]; then
    alias df='/opt/homebrew/bin/duf'
fi

if [ -f /opt/homebrew/bin/dust ]; then
    alias du='/opt/homebrew/bin/dust'
fi

if (( $+commands[starship] )); then
    eval "$(starship init zsh)"
fi

# On m1 mac - homebrew completions not picked up - add to fpath and re-run compinit
if [[ $arch == "arm" ]]; then
  fpath=(/opt/homebrew/share/zsh/site-functions(N) ${fpath})
  compinit
fi

if command -v ngrok &>/dev/null; then
  eval "$(ngrok completion)"
fi

if [ -f /opt/homebrew/bin/nvim ]; then
    alias vi=/opt/homebrew/bin/nvim
    export EDITOR=/opt/homebrew/bin/nvim
    export VISUAL=/opt/homebrew/bin/nvim
fi

if [ -f /opt/homebrew/bin/zoxide ]; then
    eval "$(zoxide init zsh)"
    alias cd="z"
fi

if [ -f /opt/homebrew/bin/fzf ]; then
    source <(fzf --zsh)
fi

if [ -d $HOME/.codeium ]; then
    # Added by Windsurf
    export PATH="$HOME/.codeium/windsurf/bin:$PATH"
fi

if [ -d /opt/homebrew/opt/rustup ]; then
    export PATH="$(brew --prefix rustup)/bin:$PATH"
fi


seal() {
  if [ -z "$1" ]; then
    echo "Usage: seal <basename or filename>"
    return 1
  fi

  local input="$1"
  local name="${input%.yaml}"

  local src="${name}.yaml"
  local dst="${name}-sealed.yaml"

  if [ -f "$dst" ]; then
    rm "$dst"
    echo "Deleted existing $dst"
  fi

  if [ -f "$src" ]; then
    kubeseal --format=yaml --controller-namespace=flux-system < "$src" >! "$dst"
    echo "Created $dst"
  else
    echo "Error: $src not found"
    return 1
  fi
}


releasetag() {
  local DATE
  DATE=$(date +"%Y%m%d")

  local PREFIX="v${DATE}"

  local LAST
  LAST=$(
    git tag -l "${PREFIX}*" \
    | sed "s/^${PREFIX}//" \
    | grep -E '^[0-9]{2}$' \
    | sort -n \
    | tail -1
  )

  local NEXT
  if [[ -z "$LAST" ]]; then
    NEXT="01"
  else
    # 10# guards against octal interpretation
    NEXT=$(printf "%02d" $((10#$LAST + 1)))
  fi

  local TAG="${PREFIX}${NEXT}"

  echo "Creating tag: $TAG"
  git tag "$TAG" || return 1
  git push origin "$TAG"
}
