local arch=$(uname -p 2>/dev/null)

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

[[ -f ~/.zshrc_local ]] && source ~/.zshrc_local

alias ls='/bin/ls -qAF'
alias mmv='noglob zmv -W'

# Ugh - prezto has -i as default
alias cp='nocorrect cp'
alias ln='nocorrect ln'
alias mv='nocorrect mv'
alias rm='nocorrect rm'


if (( $+commands[prettyping] )); then
    alias ping=prettyping
fi

if (( $+commands[htop] )); then
    alias top='sudo htop'
fi

[[ $EMACS = t ]] && unsetopt zle

if [ -f /opt/homebrew/bin/mise ]; then
  eval "$(/opt/homebrew/bin/mise activate --shims zsh)"
fi

if [ -f /opt/homebrew/bin/duf ]; then
    alias df='/opt/homebrew/bin/duf'
fi

if [ -f /opt/homebrew/bin/dust ]; then
    alias du='/opt/homebrew/bin/dust'
fi

if (( $+commands[starship] )); then
    eval "$(starship init zsh)"
fi

# On m1 mac - homebrew completions not picked up - add to fpath and re-run compinit
if [[ $arch == "arm" ]]; then
  fpath=(/opt/homebrew/share/zsh/site-functions(N) ${fpath})
  compinit
fi

if command -v ngrok &>/dev/null; then
  eval "$(ngrok completion)"
fi

if [ -f /opt/homebrew/bin/nvim ]; then
    alias vi=/opt/homebrew/bin/nvim
fi

if [ -f /opt/homebrew/bin/zoxide ]; then
    eval "$(zoxide init zsh)"
    alias cd="z"
fi

if [ -f /opt/homebrew/bin/fzf ]; then
    source <(fzf --zsh)
fi
